[package]
name = "tools"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
libbpf-rs = "0.12.0"
libc = "0.2"
plain = "0.2"
structopt = "0.3"

[build-dependencies]
libbpf-cargo = "0.9"

#[[bin]]
#name = "ethstat"
#path = "src/ethstat/bin/main.rs"
